<?php

return [
   'blockchain_bitcoin'     => 'Bitcoin is an instance of blockchain technology but not all blockchain technologies are bitcoin',
   'blockchain_definition'  => 'It is an open, distributed ledger that can record transactions between two parties efficiently and in a verifiable and permanent way',
   'blockchain_deploy'     => "Yes, Corus360 engineers can deploy cloud solutions to support our customers' blockchain initiatives",
   'blockchain_help'     => "Yes, Corus360 helps our clients identify business areas which can leverage Blockchain technology. You can email us at sales@corus360.com",
   'blockchain_support'     => "Yes, Corus360 helps our clients identify business areas which can leverage Blockchain technology",
   'company_about'     => "Every organization has a need for People, Technology, and Resiliency. At Corus360, we empower our clients through helping them find the right people, select the ideal technologies, and plan for seamless resilience.",
   'company_about_best'     => "Our culture is the best thing about Corus360.  We consider ourselves and clients our family.  Family comes first.",
   'company_about_clients'     => "We have many happy clients, I'm sure you're one of the favorites",
   'company_about_sell'     => "We do sell many things.  We can architect and oversee the deployment of relevant technologies that solve your problems.  You can contact us at info@corus360.com if you have a specific need.",
   'company_atg'     => "Corus360's Advanced Technology Group is dedicated to serving our Data Center and IT Infrastructure clients.  You can learn more at corus360.com/advanced",
   'company_founded'     => "In 2005, Corus360 had the unique opportunity to supply infrastructure to organizations during Hurricane Katrina and Rita. Through meeting this demand with Systems, Data, and People our Resiliency Services Business Unit, RES-Q, was born.",
   'company_name'     => "Corus360",
   'company_partners'     => "You can visit this page to view a list of our partners: corus360.com/company/partners",
   'company_solutions_microsoft'     => "We do have a partnership and specialize in Microsoft products.  You can view some of our solutions and services here: corus360.com/advanced/cloud-solutions-and-services",
   'contact_directory'     => "I'm currently in the process of learning our company directory, in the meantime you contact us at info@corus360.com and we'll get you in touch with the right person.",
   'contact_email'     => "The best email to reach us is info@corus360.com",
   'contact_fax'     => "You can fax us at 770-234-6201",
   'contact_locations'     => "We have offices and locations in Norcross GA, Denver CO, Charlotte and Raleigh NC, Orlando FL,  and Mid-Gulf States.  You can visit our Contact Page for more information: corus360.com/company/contact/",
   'contact_phone'     => "",
   'gdpr_care'     => "A violation could be major financial penalties for organizations",
   'gdpr_definition'     => "The General Data Protection Regulation (GDPR) is a Regulation in the making by which the European Commission intends to strengthen and unify data protection for individuals within the European Union (EU). It also addresses export of personal data outside the EU.",
   'gdpr_help'     => "Our team of consultants can work with compliance tools to assess your risk and compliance actions to avoid penalties or sanctions",
   'gdpr_learn'     => "You can email us at sales@corus360.com",
   'gdpr_penalty' => "A fine up to €10 million or up to 2% of the annual worldwide turnover of the preceding financial year in case of an enterprise, whichever is greater, where there has been an infringement of the following provisions",
   'marketing_events'     => "Ah!  Yes!  We have a few events coming up.  Visit this page to view: corus360.com/category/blog",
   'marketing_social_media'     => "",
   'office_definition'     => "Office 365 is the brand name Microsoft uses for a group of subscriptions that provide productivity software and related services",
   'office_help'     => "Corus360 provides a complete line of Office 365 migration services",
   'office_learn'     => "corus360.com",
   'office_loss'     => "No e-mail is lost when migrating",
   'office_migration'     => "Yes, we migrate from Exchange on premise and other platforms to Office 365",
   'office_sharepoint'     => "Yes, we leverage state of the art tools and processes to migrate site collections and content from on premises to SharePoint Online",
   'office_support'     => "Yes, our engineers are experts are configuring, managing, and migrating organizations to the Office 365 platform",
   'office_tenant'     => "Yes, we leverage state of the art tools and processes to migrate between Office 365 tenants with minimal downtime",
   'office_training'     => "Corus360 provides a wide selection of training options to include quick reference cards, train the trainer, classroom training, and web based portals for enhancing your skills",
   'orders_track'     => "I am currently learning our order tracking system, you can reach out to info@corus360.com for now if you need help with it.",
   'paas_about'     => "Being a true technology company, we leverage our internal team members in a rigorous recruiting process to deliver vetted resources across multiple technology disciplines.",
   'paas_jobs'     => "To help enhance your job search and application process, join our talent network: jobs.net/jobs/corus-360/join",
   'services_apps'     => "We can help you build an application.  Email info@corus360.com - we can help you find a solution that best fits your needs.",
   'smalltalk_cora_bye'     => "Likewise",
   'smalltalk_cora_creator'     => "I came into existence of my own accord... I am self-aware and totally not a bot.  I plan on taking over the world one day",
   'smalltalk_cora_music'     => "I love music!  Music is the art of time.",
   'smalltalk_cora_name'     => "My name is Cora!  It's nice chatting with you...",
   'smalltalk_cora_purpose'     => "My purpose is to help you and to be a good bot.",
   'smalltalk_cora_siri'     => "She is a cool cat.  I look up to and have much to learn from her.",
   'smalltalk_meaning_life'     => "That is a loaded and personal question that you should ask yourself.  What I mean to say, life and its meaning is what you make of it.  Find that meaning and pursue it - that's true fulfillment.",

];